microservices-demo.zip:
	wget https://github.com/microservices-demo/microservices-demo/archive/master.zip -O microservices-demo.zip

microservices-demo-master:
	unzip microservices-demo.zip "microservices-demo-master/deploy/kubernetes/manifests/*" -d .


clean:
	git clean -fxd
